# Generated by Django 4.2.8 on 2024-02-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysman', '0002_bus_specialoccasion_destination_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('arrival_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='sysman.destination')),
                ('departure_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='sysman.destination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
