# Generated by Django 4.2.8 on 2024-02-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysman', '0005_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to='busses/%Y/%m'),
        ),
        migrations.AlterUniqueTogether(
            name='trippath',
            unique_together={('departure_destination', 'arrival_destination')},
        ),
    ]
