# Generated by Django 4.2.8 on 2024-02-26 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysman', '0006_bus_image_alter_trippath_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('qr_code', models.CharField(max_length=100, null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysman.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysman.trip')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
