# Generated by Django 4.2.8 on 2024-02-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysman', '0007_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
    ]
