# Generated by Django 4.2.6 on 2024-02-27 06:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysman', '0009_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat')},
        ),
    ]
